[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cartridges"
version = "0.0.1"
description = "Lightweight and general-purpose long-context representations"
requires-python = ">=3.12"
dependencies = [
    "torch",
    "openai",
    "datasets",
    "transformers>=4.49.0,<=4.55",
    "numpy",
    "einops",
    "tqdm",
    "wandb",
    "pydrantic",
    "tiktoken",
    "peft",
    "evaluate",
    "matplotlib",
    "markdown",
    "ipykernel>=7.1.0",
    "fitz>=0.0.1.dev2",
    "frontend>=0.0.3",
    "pymupdf>=1.26.7",
    "dotenv>=0.9.9",
]

[project.scripts]
pdr = "pdr.cli:main"

[tool.setuptools]
packages = ["cartridges", "examples"]
