#!/usr/bin/env bash
# Phase 2: TF-IDF + Attention Matching continual update (backprop-free).
set -e

export TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST:-9.0}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export CARTRIDGES_DIR="${CARTRIDGES_DIR:-$(cd "$SCRIPT_DIR/../../../.." && pwd)}"
export CARTRIDGES_OUTPUT_DIR="${CARTRIDGES_OUTPUT_DIR:-$CARTRIDGES_DIR/outputs}"

CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-1}"
MODEL_NAME="${MODEL_NAME:-Qwen/Qwen3-4B-Instruct-2507}"
PHASE1_CACHE_PATH="${PHASE1_CACHE_PATH:?Set PHASE1_CACHE_PATH}"
BG_STATS_PATH="${BG_STATS_PATH:-}"
SYNTH_DATA_PATH="${SYNTH_DATA_PATH:-$CARTRIDGES_DIR/data/qasper/train/qwen_qasper_MT_task_8192.parquet}"
EVAL_DATA_PATH="${EVAL_DATA_PATH:-$CARTRIDGES_DIR/data/qasper/eval/qasper_eval_MT.parquet}"
TOP_T="${TOP_T:-64}"
GRANULARITY="${GRANULARITY:-per_layer}"
KEY_MODE="${KEY_MODE:-freeze}"
ENABLE_BETA="${ENABLE_BETA:-0}"
ENABLE_OLD_REFERENCE_GUARD="${ENABLE_OLD_REFERENCE_GUARD:-0}"
OLD_REF_DATA_PATH="${OLD_REF_DATA_PATH:-}"
OLD_REFERENCE_WEIGHT="${OLD_REFERENCE_WEIGHT:-1.0}"
MAX_REF_EXAMPLES_PER_DOC="${MAX_REF_EXAMPLES_PER_DOC:-32}"
QUERIES_PER_BATCH="${QUERIES_PER_BATCH:-all_tokens}"
USE_IDF="${USE_IDF:-1}"
if [ "$USE_IDF" = "1" ] && [ -z "$BG_STATS_PATH" ]; then
  echo "USE_IDF=1 requires BG_STATS_PATH" >&2
  exit 2
fi
RUN_NAME="${RUN_NAME:-qasper_phase2_am_sparse_top${TOP_T}_${GRANULARITY}_${KEY_MODE}}"

if [ -f "$CARTRIDGES_DIR/.venv/bin/activate" ]; then
  source "$CARTRIDGES_DIR/.venv/bin/activate"
fi

echo "=== AM-Sparse Phase 2 ==="
echo "GPU:         $CUDA_VISIBLE_DEVICES"
echo "Run name:    $RUN_NAME"
echo "Phase1:      $PHASE1_CACHE_PATH"
echo "BG stats:    $BG_STATS_PATH"
echo "Train data:  $SYNTH_DATA_PATH"
echo "top_t:       $TOP_T"
echo "granularity: $GRANULARITY"
echo "key_mode:    $KEY_MODE"
echo "beta:        $ENABLE_BETA"
echo "old guard:   $ENABLE_OLD_REFERENCE_GUARD"
echo "use_idf:     $USE_IDF"
echo "Output dir:  $CARTRIDGES_OUTPUT_DIR/<timestamp>-${RUN_NAME}/<uuid>/"
echo "========================="

export CUDA_VISIBLE_DEVICES
CARTRIDGES_DIR="$CARTRIDGES_DIR" \
CARTRIDGES_OUTPUT_DIR="$CARTRIDGES_OUTPUT_DIR" \
PHASE1_CACHE_PATH="$PHASE1_CACHE_PATH" \
BG_STATS_PATH="$BG_STATS_PATH" \
SYNTH_DATA_PATH="$SYNTH_DATA_PATH" \
EVAL_DATA_PATH="$EVAL_DATA_PATH" \
EVAL_QA_PATH="${EVAL_QA_PATH:-}" \
EVAL_MT_PATH="${EVAL_MT_PATH:-}" \
MODEL_NAME="$MODEL_NAME" \
TOP_T="$TOP_T" \
GRANULARITY="$GRANULARITY" \
KEY_MODE="$KEY_MODE" \
ENABLE_BETA="$ENABLE_BETA" \
ENABLE_OLD_REFERENCE_GUARD="$ENABLE_OLD_REFERENCE_GUARD" \
OLD_REF_DATA_PATH="$OLD_REF_DATA_PATH" \
OLD_REFERENCE_WEIGHT="$OLD_REFERENCE_WEIGHT" \
MAX_REF_EXAMPLES_PER_DOC="$MAX_REF_EXAMPLES_PER_DOC" \
QUERIES_PER_BATCH="$QUERIES_PER_BATCH" \
USE_IDF="$USE_IDF" \
RIDGE_LAMBDA="${RIDGE_LAMBDA:-1e-4}" \
RIDGE_SCALE="${RIDGE_SCALE:-spectral}" \
RIDGE_LAMBDA_MIN="${RIDGE_LAMBDA_MIN:-0.0}" \
DELTA_WEIGHT="${DELTA_WEIGHT:-1e-2}" \
RUN_NAME="$RUN_NAME" \
python "$CARTRIDGES_DIR/examples/qasper2/train/continual_am_sparse.py"

echo "=== AM-Sparse Phase 2 Done ==="
